[package]
name = "forust"
version = "0.1.0"
authors = ["Brad Urani <bradurani@gmail.com>"]
description = "Manage Procfile-based applications"
license = "MIT"
[dependencies]
clap = {version = "1", features = ["yaml"]}
iterator_to_hash_map = { version = "0.9.0" }
